const UPDATED = ['4 أكتوبر 2026', '4 October 2026'];
const EMAIL = 'heavyar.official@gmail.com';

const section = (arTitle, enTitle, ar, en, bullets = []) => ({ title: [arTitle, enTitle], text: [ar, en], bullets });

const pages = {
  terms: {
    title: ['شروط استخدام Heavyar', 'Heavyar Terms of Use'],
    intro: ['تنظم هذه الشروط استخدام سوق Heavyar السعودي للمعدات الثقيلة والخدمات المرتبطة. وهي تكمل السياسات المرتبطة ولا تنتقص من الحقوق النظامية الإلزامية.', 'These Terms govern Heavyar\'s Saudi marketplace for heavy equipment and related services. They supplement the linked policies and do not reduce mandatory statutory rights.'],
    sections: [
      section('التعريفات والنطاق', 'Definitions and scope', '«Heavyar» هي المنصة التقنية، و«العميل» طالب المعدة أو الخدمة، و«مقدم الخدمة» مالك المعدات أو المفوض بعرضها، و«السائق» أو «المشغل» مقدم خدمة القيادة أو التشغيل. يشمل «الطلب» التفاصيل والحالة والسعر المثبتة في النظام.', '"Heavyar" is the technology platform; "Customer" is the requester; "Provider" is the equipment owner or authorized lister; and "Driver" or "Operator" supplies driving or operation. A "Request" includes its system-recorded details, state and price.'),
      section('قبول الشروط والتحديثات', 'Acceptance and updates', 'باستخدام المنصة توافق على هذه الشروط والسياسات المرتبطة. تنطبق التحديثات للمستقبل بعد إشعار معقول حيث يلزم، ولا تعيد تسعير معاملة تاريخية أو تغير لقطة تجارية مثبتة بأثر رجعي.', 'By using the platform you accept these Terms and linked policies. Updates apply prospectively after reasonable notice where required and do not retroactively reprice a historical transaction or alter a locked commercial snapshot.'),
      section('الأهلية وتمثيل المنشأة', 'Capacity and business authority', 'يجب امتلاك الأهلية النظامية. ومن يستخدم Heavyar نيابة عن منشأة يقر بصلاحيته لتمثيلها. تسري الحقوق الإلزامية المناسبة على المستهلك أو الفرد أو المنشأة بحسب صفته والنظام.', 'You must have legal capacity. Anyone using Heavyar for a business represents that they are authorized to bind it. Mandatory rights apply to consumers, individuals and businesses according to status and law.'),
      section('الحساب والأمن', 'Account and security', 'يجب تقديم معلومات صحيحة ومحدثة وحماية بيانات الدخول والإبلاغ عن الاستخدام غير المصرح به. يحظر مشاركة الحساب أو انتحال صفة الغير أو استخدام بيانات لا تخصك دون سند.', 'Provide accurate, current information, protect credentials and report unauthorized use. Account sharing, impersonation and unauthorized use of another person\'s details are prohibited.'),
      section('الأدوار وطبيعة السوق', 'Roles and marketplace nature', 'تربط Heavyar العملاء ومقدمي الخدمة والسائقين وتسهل الاكتشاف والطلبات والتواصل والسجلات والمدفوعات المتاحة. قد تتحمل التزامات تشغيلية عن هذه الخدمات، لكنها لا تصبح مالكة للمعدة أو مشغلة لها أو مؤمناً لمجرد التسهيل. تبقى مسؤوليات المشاركين وفق أدوارهم والاتفاق والنظام.', 'Heavyar connects Customers, Providers and Drivers and facilitates discovery, requests, communications, records and available payments. It may have operational duties for those services but does not become the equipment owner, operator or insurer merely by facilitating them. Participant responsibility follows role, agreement and law.'),
      section('عروض المعدات', 'Equipment listings', 'يجب أن يكون العرض دقيقاً بشأن الملكية أو التفويض والفئة والمواصفات والصور والحالة والموقع التقريبي والتوفر والسعر. يجب تحديث التغيرات والإفصاح عن العيوب المعروفة، ولا يضمن النشر التوفر النهائي.', 'Listings must accurately describe ownership or authority, category, specifications, images, condition, approximate location, availability and price. Changes and known defects must be disclosed; publication does not guarantee final availability.'),
      section('الطلبات وتكوين الاتفاق', 'Requests and contract formation', 'يرسل العميل طلباً، ويقبله مقدم الخدمة أو يرفضه. ينشئ القبول التزامات بين المشاركين وفق تفاصيل الطلب وحالته وأي إضافة مشروعة متفق عليها، مع بقاء التحقق من الدفع خطوة مستقلة حيث يلزم.', 'The Customer submits a Request and the Provider accepts or rejects it. Acceptance creates obligations between participants under the Request, its state and any lawful agreed addition; payment verification remains separate where required.'),
      section('السعر والعمولة', 'Pricing and commission', 'تعرض الأسعار والرسوم والضرائب المطبقة قبل التأكيد حيثما تتوفر. العمولة الفعلية الحالية 10% ويتحملها مقدم الخدمة وفق لقطة الطلب التجارية. اقتراح 20% مسودة غير مفعلة. لا يعاد تسعير الطلب التاريخي من سعر العرض الحالي، وأي تغيير مستقبلي لا يسري بأثر رجعي.', 'Applicable prices, fees and taxes are displayed before confirmation where available. The current effective commission is 10%, Provider-paid under the Request snapshot. A proposed 20% rule is draft only and not active. Historical Requests are never repriced from current listings; future changes are not retroactive.'),
      section('الضرائب والفواتير', 'Taxes and invoices', 'يتحمل كل طرف التزاماته الضريبية بحسب صفته. تحتفظ Heavyar بسجلات المعاملة والفاتورة حيث تنطبق، وتلتزم بالمتطلبات الواجبة قانوناً، دون ادعاء اكتمال معالجة محاسبية أو تقنية غير مثبتة.', 'Each party remains responsible for taxes applicable to its status. Heavyar retains transaction and invoice records where applicable and follows legally applicable requirements, without claiming unverified accounting or technical implementation.'),
      section('الدفع المستضاف عبر Tap', 'Tap-hosted payments', 'تدخل بيانات البطاقة في تجربة Tap المستضافة للخدمات الواقعية. لا تستلم Heavyar أو تخزن رقم البطاقة الكامل أو CVV. لا يثبت الرجوع من صفحة الدفع النجاح؛ حالة الخادم بعد التحقق هي المرجع، وقد تبقى العملية معلقة أو تفشل.', 'Card details are entered in Tap\'s hosted flow for real-world services. Heavyar does not receive or store the full card number or CVV. Returning from checkout does not prove success; server-verified status is authoritative, and a payment may remain pending or fail.'),
      section('التسوية لمقدم الخدمة', 'Provider settlement', 'السجل التجاري الداخلي لا يثبت تحويل الأموال. Tap Marketplace أو Split غير مفعلة أو مثبتة حالياً، ولا يجوز اعتبار رصيد أو مستحق داخلي إثبات صرف.', 'An internal commercial record does not prove funds transfer. Tap Marketplace or Split is not currently enabled or verified, and an internal balance or receivable is not payout evidence.'),
      section('الإلغاء والاسترجاع', 'Cancellation and refunds', 'تطبق سياسة الإلغاء والاسترجاع بحسب مرحلة الطلب والدفع وبدء الخدمة. لا تضمن Heavyar استرجاعاً آلياً أو فورياً أو بنسبة ثابتة، وتخضع المطالبة الحالية للمراجعة التشغيلية مع حفظ الحقوق الإلزامية.', 'The Cancellation and Refund Policy applies by Request stage, payment and commencement. Heavyar does not promise an automatic, instant or fixed-percentage refund. Current claims require operational review, preserving mandatory rights.'),
      section('التسليم والفحص وحالة المعدات', 'Handover, inspection and condition', 'يوثق الأطراف الحالة والملحقات والعدادات والعيوب عند التسليم والإرجاع. يبقى مقدم الخدمة مسؤولاً عن الوصف الصادق والصيانة اللازمة، ولا تنشئ Heavyar ضماناً ميكانيكياً مستقلاً.', 'Participants should document condition, accessories, meters and defects at handover and return. The Provider remains responsible for truthful condition and required maintenance; Heavyar does not create a separate mechanical warranty.'),
      section('الموقع والنقل والتأخير', 'Site, transport and delay', 'يقدم العميل معلومات دقيقة عن موقع العمل والوصول والمخاطر المعروفة. ويتفق الأطراف على النقل والتسليم والوقود والمواد الاستهلاكية. يبلغ التأخير أو عدم الحضور فوراً ويقيم بحسب السبب والدليل.', 'The Customer must accurately describe the job site, access and known hazards. Participants agree transport, delivery, fuel and consumables. Delay or no-show must be reported promptly and is assessed by cause and evidence.'),
      section('التشغيل والصيانة والأعطال', 'Operation, maintenance and breakdown', 'لا يشغل المعدات الثقيلة أو المنظمة إلا شخص مؤهل. يلتزم مقدم الخدمة بالصيانة والتعليمات والإفصاح عن العيوب، ويلتزم المستخدم بالاستخدام الصحيح وإيقاف المعدة عند الخطر وتوثيق العطل وإبلاغ الأطراف.', 'Only a qualified person may operate heavy or regulated equipment. Providers maintain equipment and disclose instructions and defects; users operate correctly, stop on hazard, document breakdown and notify relevant parties.'),
      section('السلامة والتصاريح والتأمين', 'Safety, permits and insurance', 'يتحمل كل طرف التراخيص والتصاريح وبطاقات التشغيل ومعدات الوقاية والتأمين المطلوبة لنشاطه أو موقعه أو معدته. Heavyar لا تصبح شركة تأمين ولا تعوض عن تغطية واجبة.', 'Each party is responsible for licences, permits, operating cards, PPE and insurance required for its activity, site or equipment. Heavyar does not become an insurer or replace required coverage.'),
      section('الحوادث والأضرار والسرقة', 'Accidents, damage and theft', 'تقدم السلامة ويبلغ الطرف المختص والمؤمن والجهات الرسمية بحسب الحالة، وتحفظ الصور والتقارير. تحدد مسؤولية الإصابة أو الضرر أو الفقد أو السرقة وفق السلوك والاتفاق والنظام. لا توجد وديعة أو إعفاء أضرار مفترض من Heavyar.', 'Safety comes first. Notify the responsible party, insurer and authorities as applicable and preserve reports and photos. Liability for injury, damage, loss or theft follows conduct, agreement and law. Heavyar provides no assumed deposit or damage waiver.'),
      section('المخالفات والغرامات', 'Violations and fines', 'تتبع مسؤولية المخالفة المرورية أو التشغيلية أو البلدية النظام والسلوك الذي أنشأها، ولا تخصص Heavyar الغرامة آلياً لمجرد دور الشخص في المنصة.', 'Responsibility for traffic, operating, municipal or other violations follows law and the conduct causing them. Heavyar does not allocate a fine automatically merely by platform role.'),
      section('المحادثات والتقييمات والمحتوى', 'Chat, reviews and content', 'يجب أن يكون المحتوى مشروعاً وصادقاً ومتعلقاً بالمعاملة. تمنح Heavyar ترخيصاً محدوداً لاستضافة المحتوى وعرضه لتشغيل الخدمة مع بقاء حقوق صاحبه، ويجوز تقييد المضلل أو المسيء أو المخالف.', 'Content must be lawful, genuine and transaction-related. You grant Heavyar a limited licence to host and display it to operate the service while rights remain with the owner. Misleading, abusive or unlawful content may be restricted.'),
      section('السلوك المحظور', 'Prohibited conduct', 'يحظر الاحتيال والتزوير وانتحال الهوية والمعدات المسروقة والتحايل على ضوابط المنصة والاحتيال في الدفع أو الاعتراضات والهجمات الأمنية. تكمل سياسة الاستخدام المقبول هذه الالتزامات.', 'Fraud, forgery, impersonation, stolen equipment, circumvention of platform controls, payment or chargeback abuse and security attacks are prohibited. The Acceptable Use Policy supplements these duties.'),
      section('الملكية الفكرية وخدمات الغير', 'Intellectual property and third parties', 'تحمى برامج Heavyar وعلاماتها ومحتواها. يحظر النسخ أو الهندسة العكسية إلا بالقدر الذي لا يجوز تقييده نظاماً. تخضع خدمات Firebase وCloudflare وCloudinary وExpo وResend وTap لشروطها وتوفرها.', 'Heavyar software, marks and content are protected. Copying or reverse engineering is prohibited except where restriction is unlawful. Firebase, Cloudflare, Cloudinary, Expo, Resend and Tap remain subject to their terms and availability.'),
      section('التوفر والتعليق والإنهاء', 'Availability, suspension and termination', 'قد تتوقف الخدمة للصيانة أو الأعطال أو القوة القاهرة. يجوز تقييد حساب أو عرض أو طلب لحماية المستخدمين أو التحقيق أو الامتثال بصورة متناسبة، مع الحقوق ووسائل المراجعة النظامية.', 'The service may be interrupted for maintenance, faults or force majeure. Accounts, listings or Requests may be proportionately restricted for safety, investigation or compliance, subject to statutory rights and review channels.'),
      section('حذف الحساب والاحتفاظ', 'Account deletion and retention', 'يبدأ الحذف داخل التطبيق من الملف الشخصي أو الإعدادات. يقفل الحساب وتبدأ المعالجة، وقد تبقى سجلات محدودة ومقيدة للمعاملات أو المحاسبة أو النزاعات أو منع الاحتيال حيث يوجب النظام أو الغرض المشروع. صفحة الموقع معلوماتية ولا تطلب كلمة مرور.', 'Deletion starts in-app from Profile or Settings. The account is locked and processing begins; limited restricted transaction, accounting, dispute or anti-fraud records may remain where law or a legitimate purpose requires. The website page is informational and never requests a password.'),
      section('حدود المسؤولية', 'Liability limits', 'إلى أقصى حد يسمح به النظام، لا تضمن Heavyar سلوك مستخدم أو حالة معدة لا تسيطر عليها أو استمرار خدمة خارجية. لا تستبعد هذه الشروط المسؤولية التي لا يجوز استبعادها أو الاحتيال أو التعمد أو حقوق المستهلك الإلزامية، ولا تستبعد الخسائر غير المباشرة إلا بالقدر الجائز.', 'To the maximum extent permitted by law, Heavyar does not guarantee user conduct, equipment outside its control or uninterrupted third-party services. Nothing excludes non-excludable liability, fraud, intentional misconduct or mandatory consumer rights; indirect loss is excluded only to the lawful extent.'),
      section('التعويض المحدود والقوة القاهرة', 'Scoped indemnity and force majeure', 'إلى الحد المسموح، يتحمل المستخدم الخسائر المعقولة والمثبتة الناتجة مباشرة عن نشاطه غير المشروع أو معلوماته الكاذبة أو عرضه غير المفوض أو إساءة استخدامه، مع السببية والتناسب. يعفى التأخير الخارج عن السيطرة المعقولة بالقدر الذي يقره النظام مع واجب التخفيف.', 'To the lawful extent, a user is responsible for reasonable proven loss directly caused by unlawful conduct, false information, unauthorized listing or misuse, subject to causation and proportionality. Delay outside reasonable control is excused only as recognized by law and subject to mitigation.'),
      section('الإشعارات وقابلية الفصل', 'Notices and severability', 'يجوز إرسال الإشعارات إلكترونياً. لا ينقل المستخدم التزامه بما يضر الغير دون موافقة لازمة. بطلان حكم لا يبطل البقية، وعدم إنفاذ حق مرة لا يعد تنازلاً دائماً.', 'Notices may be electronic. Users may not transfer obligations to another\'s detriment without required consent. An invalid clause does not invalidate the rest, and one failure to enforce is not a permanent waiver.'),
      section('القانون والاختصاص والتواصل', 'Law, jurisdiction and contact', 'تخضع الشروط لأنظمة المملكة العربية السعودية. يمكن البدء بالدعم دون منع التوجه إلى وزارة التجارة أو سدايا أو البنك أو Tap أو شركة التأمين أو المحكمة أو الجهة السعودية المختصة. إذا منح النظام حقاً أكبر غير قابل للتنازل فإنه يسود.', 'These Terms are governed by the laws of the Kingdom of Saudi Arabia. Support may be the first step without preventing access to the Ministry of Commerce, SDAIA, a bank, Tap, insurer, court or competent Saudi authority. Any greater non-waivable statutory right prevails.'),
    ],
  },
  privacy: {
    title: ['سياسة خصوصية Heavyar', 'Heavyar Privacy Policy'],
    intro: ['توضح هذه السياسة معالجة البيانات وفق نظام حماية البيانات الشخصية السعودي ومبادئ تحديد الغرض وتقليل البيانات والشفافية والأمن.', 'This Policy explains processing under the Saudi Personal Data Protection Law and the principles of purpose limitation, minimization, transparency and security.'],
    sections: [
      section('المتحكم والنطاق', 'Controller and scope', 'Heavyar هي المتحكم في البيانات التي تحدد أغراض ووسائل معالجتها لتشغيل المنصة. تشمل السياسة العملاء ومقدمي الخدمة والسائقين وزوار الموقع ومستخدمي الدعم.', 'Heavyar is the controller for data whose purposes and means it determines to operate the platform. This Policy covers Customers, Providers, Drivers, website visitors and support users.'),
      section('المصادر', 'Sources', 'نحصل على البيانات منك عند التسجيل والملف والعروض والطلبات والمحادثات والدعم، ومن استخدام الجهاز والخدمة، ومن الطرف المقابل والمعالجين والجهات المختصة عند وجود أساس نظامي.', 'We receive data from registration, profiles, listings, Requests, chat and support; device and service use; counterparties and processors; and competent authorities where lawfully justified.'),
      section('الحساب والاتصال', 'Account and contact data', 'قد نعالج الاسم والبريد والجوال ومعرف المستخدم وصورة الملف واللغة والدور وحالة الحساب.', 'We may process name, email, phone number, user identifier, profile image, language, role and account status.'),
      section('المنشأة والمعدات والموقع', 'Business, equipment and location', 'قد نعالج نوع مقدم الخدمة ورقم السجل التجاري والمعلومات التجارية المدخلة، ومواصفات المعدات وصورها وملكيتها أو التفويض وحالتها وسعرها وتوفرها، والمنطقة والمدينة والموقع التقريبي الذي يدخله المستخدم.', 'We may process provider type, commercial-registration number and submitted business data; equipment specifications, images, ownership or authority, condition, price and availability; and user-entered region, city and approximate location.'),
      section('الطلبات والمحتوى', 'Requests and content', 'نعالج طلبات المعدات والسائقين وحالات التأجير والتسليم والإكمال، والمحادثات والتقييمات والشكاوى والأدلة والصور والإشعارات وتفضيلاتها.', 'We process equipment and Driver Requests, rental, handover and completion states, chat, ratings, complaints, evidence, images, notifications and preferences.'),
      section('البيانات التقنية والأمنية', 'Technical and security data', 'قد نعالج رموز الإشعار ومعرفات التثبيت أو الطلب والسجلات وعنوان الشبكة وأحداث الأمن والتشخيص اللازم للتشغيل ومنع الاحتيال، لا للتتبع الإعلاني عبر التطبيقات.', 'We may process push tokens, installation or request identifiers, logs, network address, security events and diagnostics needed for operation and fraud prevention, not cross-app advertising tracking.'),
      section('المدفوعات', 'Payments', 'نعالج مبلغ المعاملة وعملتها وحالتها ومراجعها للطلب والفاتورة والدعم. تدخل بيانات البطاقة لدى Tap في تدفق مستضاف؛ ولا تخزن Heavyar رقم البطاقة الكامل أو CVV.', 'We process transaction amount, currency, status and references for Requests, invoices and support. Card data is entered with Tap in a hosted flow; Heavyar does not store the full card number or CVV.'),
      section('ما لا يجمعه الإصدار الحالي', 'Data not collected now', 'لا يجمع إصدار iOS الحالي الفئات التالية، ولا يجوز تفسير صلاحيات أو ميزات مستقبلية على أنها مفعلة الآن.', 'The current iOS release does not collect the following categories, and future capabilities must not be treated as active now.', [['هوية وطنية أو جواز سفر أو مستند هوية حكومي.', 'National ID, passport or government identity document.'], ['رقم حساب بنكي أو IBAN أو بيانات بنك للصرف.', 'Bank-account number, IBAN or payout-bank details.'], ['الموقع الجغرافي الدقيق أو جهات الاتصال أو بيانات الميكروفون.', 'Precise geolocation, contacts or microphone data.'], ['بيانات للتتبع الإعلاني عبر التطبيقات.', 'Data for cross-app advertising tracking.']]),
      section('الأغراض والأسس النظامية', 'Purposes and lawful bases', 'نستخدم البيانات للمصادقة وتشغيل السوق والطلبات والدفع المستضاف والتواصل والدعم والإشعارات ومنع الاحتيال وحماية الحقوق والامتثال. يعتمد الأساس بحسب الحالة على الخدمة المطلوبة أو الالتزام النظامي أو الموافقة أو المصلحة المشروعة التي لا تتغلب عليها حقوق الشخص.', 'Data supports authentication, marketplace operation, Requests, hosted payments, communications, support, notifications, fraud prevention, rights protection and compliance. The basis may be requested service, legal duty, consent or legitimate interest not overridden by the person\'s rights.'),
      section('تقليل البيانات والدقة', 'Minimization and accuracy', 'نجمع ما يلزم للغرض ونراجع إمكانية تقليله، وعلى المستخدم تحديث بياناته. لا تستخدم البيانات لغرض غير متوافق دون أساس وإفصاح مناسب.', 'We collect what is necessary, review minimization and ask users to keep data current. Data is not used for an incompatible purpose without an appropriate basis and disclosure.'),
      section('المشاركة في السوق', 'Marketplace sharing', 'يظهر للطرف المقابل الحد اللازم لتنفيذ الطلب، مثل بيانات العرض والتواصل والموقع التشغيلي المناسب والحالة. لا يجوز استخدام البيانات خارج المعاملة أو كشفها دون سند.', 'Counterparties receive only what is needed to perform a Request, such as listing, communication, appropriate operational location and status. Data may not be used outside the transaction or disclosed without authority.'),
      section('المعالجون', 'Processors', 'نستخدم عند الحاجة Firebase للمصادقة والبيانات والإشعارات، وCloudflare للاستضافة والحماية، وCloudinary للوسائط، وExpo للتطبيق والإشعارات، وResend للبريد، وTap للدفع المستضاف.', 'Where needed, we use Firebase for authentication, data and notifications; Cloudflare for hosting and protection; Cloudinary for media; Expo for app and notifications; Resend for email; and Tap for hosted payments.'),
      section('الإفصاح النظامي', 'Lawful disclosure', 'قد نفصح عن بيانات محددة لجهة مختصة أو محكمة عند طلب صحيح أو التزام نظامي، أو بصورة متناسبة لحماية الحقوق والسلامة ومنع الاحتيال. لا نبيع البيانات الشخصية.', 'Specific data may be disclosed to a competent authority or court under a valid request or legal duty, or proportionately to protect rights, safety and prevent fraud. We do not sell personal data.'),
      section('النقل خارج المملكة', 'Cross-border processing', 'قد تستلزم بنية بعض المعالجين معالجة خارج المملكة. يجب تقييم الغرض والضرورة ومستوى الحماية والضمان المناسب وتقليل البيانات وفق نظام حماية البيانات ولائحة النقل. لا يعني ذلك نقل كل الفئات.', 'Some processors may require processing outside Saudi Arabia. Purpose, necessity, protection level, appropriate safeguards and minimization must be assessed under the PDPL and transfer regulation. This does not mean every category is transferred.'),
      section('الاحتفاظ والإتلاف', 'Retention and destruction', 'نحتفظ بكل فئة للمدة اللازمة للغرض والالتزام والمعاملة والمحاسبة ومنع الاحتيال أو النزاع، ثم نحذفها أو نتلفها أو نخفي هويتها أو نقيدها. لا ندعي مدة موحدة غير مطبقة. قد تبقى نسخة احتياطية محدودة حتى الاستبدال الآمن مع تقييد استخدامها.', 'Each category is kept only as needed for purpose, legal duty, transaction, accounting, fraud prevention or dispute, then deleted, destroyed, anonymized or restricted. We do not invent a single unimplemented period. Limited backups may remain until secure rotation with restricted use.'),
      section('حذف الحساب', 'Account deletion', 'يبدأ الحذف داخل التطبيق من الملف الشخصي أو الإعدادات. يقفل الحساب وتبدأ المعالجة، وقد تبقى سجلات معاملات أو فواتير أو استرجاعات أو تدقيق أو نزاعات محدودة حيث يلزم. عند تعذر الدخول تواصل مع الدعم ولا ترسل كلمة مرور.', 'Deletion starts in-app from Profile or Settings. The account is locked and processing begins; limited transaction, invoice, refund, audit or dispute records may remain where necessary. If access is unavailable, contact support and never send a password.'),
      section('الأمن والحوادث', 'Security and incidents', 'نستخدم ضوابط وصول وصلاحيات وفصل أسرار وتشفير النقل وسجلات تدقيق ومراقبة بحسب المخاطر. لا توجد وسيلة آمنة مطلقاً. نقيم الحوادث ونحتويها ونخطر الجهات والأشخاص متى أوجب النظام.', 'We use risk-appropriate access controls, permissions, secret separation, transport encryption, audit records and monitoring. No method is absolutely secure. We assess and contain incidents and notify authorities and people where required.'),
      section('حقوق صاحب البيانات', 'Data-subject rights', 'وفق النظام والقيود المشروعة يحق للشخص معرفة أساس وغرض المعالجة، والوصول والحصول على نسخة واضحة، والتصحيح والإكمال والتحديث، وطلب الإتلاف عند انطباقه، وسحب الموافقة عندما تكون الأساس دون أثر رجعي. قد نتحقق من الهوية.', 'Subject to law and lawful limits, a person may be informed of basis and purpose; access data and receive a clear copy; request correction, completion and update; request destruction where applicable; and withdraw consent when it is the basis without retroactive effect. Identity may be verified.'),
      section('الشكاوى', 'Complaints', 'يمكن ممارسة الحقوق والاستفسار والشكوى عبر الحساب أو البريد أدناه. لا يمنع ذلك التوجه إلى سدايا أو الجهة السعودية المختصة وفق الإجراءات النظامية.', 'Rights, questions and complaints may be submitted in-account or at the email below. This does not prevent escalation to SDAIA or another competent Saudi authority.'),
      section('الأطفال والأهلية', 'Children and capacity', 'المنصة ليست موجهة للأطفال أو لمن لا يملك الأهلية النظامية لهذه الخدمات. يمكن طلب تقييد أو حذف بيانات شخص غير مؤهل قدمت دون سند مناسب وفق النظام.', 'The platform is not directed to children or persons lacking capacity for these services. Data submitted without an appropriate basis for a person lacking capacity may be restricted or deleted subject to law.'),
      section('القرارات الآلية والإعلانات والموقع', 'Automation, ads and website storage', 'لا تستخدم Heavyar حالياً التنميط الآلي وحده لاتخاذ قرار قانوني أو مماثل الأثر، ولا تبيع البيانات أو تستخدم إعلاناً سلوكياً. يستخدم الموقع التخزين المحلي الضروري للغة والوظائف الأساسية ولا ندعي تحليلات غير مطبقة.', 'Heavyar does not currently use solely automated profiling for legal or similarly significant decisions, sell data or use behavioral advertising. The website uses necessary local storage for language and core functions and does not claim unimplemented analytics.'),
      section('التغييرات والتواصل', 'Changes and contact', 'ننشر تاريخ التحديث ونقدم إشعاراً مناسباً بالتغيير الجوهري حيث يلزم. لا ترسل كلمات المرور أو بيانات البطاقة عند التواصل.', 'We publish the update date and provide appropriate notice of material changes where required. Never send passwords or card details when contacting us.'),
    ],
  },
  'refund-policy': {
    title: ['سياسة الإلغاء والاسترجاع', 'Cancellation and Refund Policy'],
    intro: ['تعكس هذه السياسة الوظائف الحالية. تنفيذ الاسترجاع غير جاهز آلياً، ولا تَعِد Heavyar باسترجاع مضمون أو فوري.', 'This Policy reflects current behavior. Refund execution is not automated or operationally complete, and Heavyar does not promise guaranteed or instant refunds.'],
    sections: [
      section('قبل قبول مقدم الخدمة', 'Before Provider acceptance', 'يمكن للعميل إلغاء الطلب المعلق من التطبيق مجاناً، ولا تفرض Heavyar رسوم إلغاء في هذه المرحلة.', 'A Customer may cancel a pending Request in-app free of charge. Heavyar imposes no cancellation fee at this stage.'),
      section('بعد القبول وقبل الدفع', 'After acceptance and before payment', 'يمكن للعميل الإلغاء مجاناً وفق السياسة الحالية بعد قبول مقدم الخدمة وقبل الدفع، مع إبلاغ الطرف الآخر لتقليل التكلفة الفعلية.', 'Under the current policy, the Customer may cancel free of charge after provider acceptance and before payment, with notice to reduce actual cost.'),
      section('بعد الدفع وقبل بدء الخدمة', 'After payment and before service', 'لا توجد نسبة استرجاع تلقائية ثابتة. تراجع الأهلية وفق السبب وحالة الدفع والتكاليف الفعلية المثبتة والمعلنة مسبقاً التي يجوز الاحتفاظ بها. لا تفترض Heavyar وجود رسوم بوابة أو تكلفة غير قابلة للاسترجاع.', 'There is no automatic fixed refund percentage. Eligibility depends on reason, payment status and proven, pre-disclosed actual costs that may lawfully be retained. Heavyar does not presume a gateway fee or non-refundable cost exists.'),
      section('بعد بدء الخدمة', 'After service starts', 'لا يعد باسترجاع كامل تلقائي. تراجع المدة أو الاستخدام والمنفعة والتوقف والأعطال والأضرار وأدلة الطرفين والحقوق الإلزامية.', 'No automatic full refund is promised. Review considers duration or use, benefit, interruption, breakdown, damage, both parties\' evidence and mandatory rights.'),
      section('إلغاء مقدم الخدمة أو السائق', 'Provider or Driver cancellation', 'إذا ألغى مقدم الخدمة قبل البدء أو تعذر توفير المعدة، تراجع إعادة مبالغ الخدمة غير المقدمة. ويقيم إلغاء السائق وفق أثره الفعلي والبديل المتاح، دون الانتقاص من حق واجب.', 'If the Provider cancels before commencement or cannot supply equipment, repayment for the undelivered service is reviewed. Driver cancellation is assessed by actual impact and available replacement, without reducing mandatory rights.'),
      section('معدات غير مطابقة أو غير آمنة', 'Misdescribed or unsafe equipment', 'أبلغ فوراً ولا تستخدم معدة تبدو خطرة. قد تدعم الصور والفحص والتقارير المطالبة عند اختلاف المعدة جوهرياً أو عدم صلاحيتها للغرض المتفق عليه.', 'Report promptly and do not use apparently unsafe equipment. Photos, inspection and reports may support a claim where equipment materially differs or is unfit for the agreed purpose.'),
      section('التأخير وعدم الحضور والقوة القاهرة', 'Delay, no-show and force majeure', 'تراجع المسؤولية بحسب السبب والإشعارات والأدلة وما قدم فعلياً. تعامل القوة القاهرة وفق النظام مع تخفيف الضرر، ولا تسقط حقاً إلزامياً في خدمة لم تقدم.', 'Responsibility is reviewed by cause, notices, evidence and actual performance. Force majeure is handled under law with mitigation and does not remove a mandatory right for an undelivered service.'),
      section('الخصم المكرر أو الفاشل', 'Duplicate or failed payment', 'لا يثبت الرجوع من Tap نجاح الخصم؛ يتحقق الخادم من الحالة. أبلغ عن التكرار أو التعليق مع مرجع الطلب ودليل البنك، دون إرسال رقم بطاقة كامل أو CVV.', 'Returning from Tap does not prove a charge; the server verifies status. Report duplicates or pending payments with the Request reference and bank evidence, never a full card number or CVV.'),
      section('المراجعة والتنفيذ', 'Review and execution', 'أرسل رقم الطلب والسبب والمبلغ والتاريخ والأدلة. قد تطلب Heavyar معلومات من الأطراف أو Tap. التنفيذ الحالي يدوي وغير جاهز كميزة آلية، وقد يعتمد زمن وصول المبلغ بعد الموافقة على البنك ومزود الدفع.', 'Provide Request number, reason, amount, date and evidence. Heavyar may seek information from participants or Tap. Current execution is manual and not ready as an automated feature; after approval, receipt timing may depend on the bank and provider.'),
      section('النزاع والتصعيد', 'Dispute and escalation', 'يمكن التوجه للدعم أو مصدر البطاقة أو Tap أو الجهة المختصة بحسب الحالة. لا تضمن مراجعة الدعم نتيجة ولا تمنع مساراً نظامياً.', 'Support, the card issuer, Tap or a competent authority may be contacted as applicable. Support review does not guarantee an outcome or prevent a statutory channel.'),
      section('الحقوق وعدم الرجعية', 'Rights and non-retroactivity', 'إذا منح النظام السعودي حقاً إلزامياً أكبر فإنه يسود. أي مهلة أو رسم أو نسبة مستقبلية يجب الإفصاح عنها قبل انطباقها ولا تعيد كتابة معاملة سابقة.', 'Any greater mandatory right under Saudi law prevails. A future notice period, fee or percentage must be disclosed before application and cannot rewrite a past transaction.'),
    ],
  },
  disputes: {
    title: ['سياسة الشكاوى والنزاعات', 'Complaints and Disputes Policy'],
    intro: ['تقدم Heavyar مراجعة دعم تشغيلية وليست محكمة أو محكماً أو شركة تأمين أو جهة إنفاذ.', 'Heavyar provides operational support review and is not a court, arbitrator, insurer or law-enforcement authority.'],
    sections: [
      section('تقديم الشكوى', 'Submitting a complaint', 'أرسل رقم الطلب ووصفاً محدداً والنتيجة المطلوبة من الحساب إن أمكن. لا ترسل كلمة مرور أو رقم بطاقة كامل أو CVV أو بيانات غير لازمة.', 'Where possible, submit from the account with the Request number, a specific description and requested outcome. Never send a password, full card number, CVV or unnecessary data.'),
      section('الأدلة وحفظ السجل', 'Evidence and preservation', 'احتفظ بالصور والمحادثات والفواتير وتقارير التسليم والفحص والأعطال والحوادث. يجوز تقييد حذف السجلات ذات الصلة مؤقتاً للتحقيق أو التزام نظامي.', 'Keep photos, messages, invoices, handover, inspection, breakdown and incident reports. Deletion of relevant records may be temporarily restricted for investigation or legal duty.'),
      section('المراجعة والنتيجة', 'Review and outcome', 'قد تطلب Heavyar ردوداً وتقارنها بحالة النظام واللقطات التجارية والدفع المتحقق. قد تغلق الشكوى أو تطلب تصحيحاً أو تقيد حساباً أو تحيل الموضوع، دون إصدار حكم أو ضمان تعويض.', 'Heavyar may request responses and compare them with system state, commercial snapshots and verified payment. It may close a case, request correction, restrict an account or refer the matter, without issuing judgment or guaranteeing compensation.'),
      section('الاحتيال والإساءة', 'Fraud and abuse', 'تعالج ادعاءات الحسابات الوهمية والتزوير والمعدات المسروقة والاحتيال في الدفع والتقييمات الكاذبة بحسب الخطر، وقد تقيد الحساب وتحفظ الأدلة وتبلغ الجهة المختصة عند وجود أساس.', 'Fake accounts, forgery, stolen equipment, payment fraud and manipulated ratings are handled according to risk. Accounts may be restricted, evidence preserved and authorities notified where justified.'),
      section('المعدات والحوادث والتأمين', 'Equipment, incidents and insurance', 'يبلغ الخطر أو الإصابة أو الضرر أو السرقة فوراً للجهة المختصة والمؤمن والطرف الآخر. سجلات Heavyar قد تساند التحقيق ولا تحل محل تقرير الشرطة أو الخبير أو قرار المؤمن.', 'Danger, injury, damage or theft must be reported promptly to the authority, insurer and counterparty. Heavyar records may assist but do not replace police, expert or insurer determinations.'),
      section('الدفع والاعتراض البنكي', 'Payments and chargebacks', 'تراجع Heavyar حالة الخادم وسجل Tap المتاح. يبقى مسار مصدر البطاقة أو Tap، ويحظر الاعتراض الاحتيالي بعد خدمة صحيحة. القيد الداخلي لا يثبت استرجاعاً أو صرفاً.', 'Heavyar reviews server status and available Tap records. Card-issuer and Tap channels remain available, and fraudulent chargebacks after proper service are prohibited. An internal entry does not prove refund or payout.'),
      section('السلطات والمسارات المستقلة', 'Authorities and separate channels', 'يجوز التوجه إلى وزارة التجارة أو سدايا أو الشرطة أو المرور أو الجهة التنظيمية أو المحكمة السعودية المختصة. لا يلزم استنفاد الدعم عند وجود حق مباشر أو طارئ.', 'A matter may be taken to the Ministry of Commerce, SDAIA, police, traffic, regulator or competent Saudi court. Support need not be exhausted where a direct right or emergency exists.'),
      section('الخصوصية والحقوق', 'Privacy and rights', 'تدار الشكوى بأقل إفصاح لازم مع حق الرد والحقوق الإلزامية. لا تنشر بيانات الطرف الآخر، وتواصل عبر البريد أدناه بمرجع الطلب.', 'Complaints use minimum necessary disclosure while preserving response and mandatory rights. Do not publish another person\'s data; contact the email below with the Request reference.'),
    ],
  },
  'provider-terms': {
    title: ['شروط مقدمي المعدات والخدمات', 'Equipment Provider Terms'],
    intro: ['تكمل هذه الشروط شروط الاستخدام لكل مالك معدات أو مفوض يعرضها أو يقدم خدمة مرتبطة.', 'These terms supplement the Terms of Use for every equipment owner or authorized lister providing related services.'],
    sections: [
      section('الملكية والتفويض', 'Ownership and authority', 'يجب امتلاك المعدة أو تفويض صالح قابل للإثبات. يحظر عرض أصل مسروق أو محل نزاع أو مقيد بما يمنع التصرف دون إفصاح وموافقة لازمة.', 'Own the equipment or hold provable valid authority. Stolen, disputed or restricted assets may not be listed without required disclosure and consent.'),
      section('السجل والتراخيص', 'Registration and licensing', 'يحافظ مقدم الخدمة على السجلات والتراخيص والتصاريح وبطاقات التشغيل المطلوبة حيث يلزم. بيانات السجل المدخلة معلومات عمل عادية ما لم تعرض شارة تحقق محددة.', 'Maintain registrations, licences, permits and operating cards where required. Submitted registration data is ordinary business information unless a specific verification badge is displayed.'),
      section('دقة العرض والتوفر', 'Listing accuracy and availability', 'يجب تحديث الفئة والموديل والصور والحالة والموقع والسعر والملحقات والتوفر والإفصاح عن العيوب والقيود. يوقف العرض عند تعذر التنفيذ.', 'Keep category, model, images, condition, location, price, accessories and availability current and disclose defects and limits. Pause a listing when fulfilment is unavailable.'),
      section('التسعير والعمولة والضريبة', 'Pricing, commission and tax', 'العمولة الحالية 10% على مقدم الخدمة وفق لقطة الطلب؛ 20% مسودة غير مفعلة. يبقى مقدم الخدمة مسؤولاً عن ضريبته، ولا يعيد تسعير طلباً تاريخياً.', 'The current commission is 10%, Provider-paid under the Request snapshot; 20% is draft and not active. Providers remain responsible for their taxes and may not reprice historical Requests.'),
      section('القبول والتنفيذ', 'Acceptance and fulfilment', 'لا يقبل الطلب إلا عند القدرة على التنفيذ في الوقت والموقع والشروط. يجب تأكيد التسليم والإكمال بصدق وعدم التحايل على ضوابط المنصة.', 'Accept only when able to perform at the stated time, location and conditions. Confirm handover and completion truthfully and do not evade platform controls.'),
      section('الصيانة والسلامة والفحص', 'Maintenance, safety and inspection', 'يجب أن تكون المعدة مصانة وآمنة وصالحة للغرض المعلن، مع تعليمات وتحذيرات وسجلات مطلوبة وفحص معقول وتوثيق عند التسليم والإرجاع.', 'Equipment must be maintained, safe and fit for the represented purpose, with required instructions, warnings, records, reasonable inspection and condition documentation.'),
      section('النقل والأعطال', 'Transport and breakdown', 'يوضح مقدم الخدمة مسؤوليات النقل والتحميل والتفريغ والوقود والمواد الاستهلاكية، ويبلغ التأخير أو العطل ويتخذ إجراء السلامة والإصلاح أو البديل المتفق عليه.', 'Clarify transport, loading, unloading, fuel and consumables. Report delay or breakdown and take safe repair or agreed replacement action.'),
      section('السائقون والمشغلون', 'Drivers and operators', 'إذا وفر مقدم الخدمة سائقاً أو مشغلاً فيجب أن يكون مؤهلاً ومرخصاً حيث يلزم ولائقاً وملتزماً بالسلامة. يحظر مشاركة المؤهلات أو إسناد التشغيل لغير مصرح.', 'A supplied Driver or Operator must be qualified, licensed where required, fit and safety-compliant. Credential sharing or unauthorized operation is prohibited.'),
      section('التأمين والحوادث والأضرار', 'Insurance, incidents and damage', 'يحافظ على التأمين المطلوب ويبلغ المؤمن والجهات المختصة عن الحادث أو الإصابة أو السرقة. توثق الأضرار وتحدد المسؤولية بالسبب والدليل والاتفاق والنظام، لا بافتراض آلي.', 'Maintain required insurance and notify the insurer and authorities of accidents, injury or theft. Damage responsibility follows cause, evidence, agreement and law, not an automatic assumption.'),
      section('الإلغاء وعدم التوفر', 'Cancellation and unavailability', 'لا يلغى طلب مقبول بلا سبب مشروع وإشعار سريع. عند تعذر المعدة قبل البدء يتعاون مقدم الخدمة في معالجة مبالغ الخدمة غير المقدمة وحقوق العميل.', 'Do not cancel an accepted Request without legitimate reason and prompt notice. If equipment is unavailable before commencement, cooperate in addressing undelivered-service amounts and Customer rights.'),
      section('الدفع والتسوية', 'Payment and settlement', 'سجل Heavyar ليس إثبات صرف. Tap Marketplace أو Split غير مفعلة أو مثبتة. يحظر طلب بيانات بطاقة العميل أو CVV أو الادعاء بالاستلام قبل تحقق التسوية.', 'A Heavyar record is not payout proof. Tap Marketplace or Split is not enabled or verified. Never request Customer card data or CVV or claim receipt before actual settlement.'),
      section('السلوك والتعليق', 'Conduct and suspension', 'يحظر الغش والتزوير والتقييمات المصطنعة والمحتوى المنتهك وبيع البيانات. يجوز إزالة عرض أو تقييد حساب للخطر أو المخالفة أو التحقيق بصورة متناسبة.', 'Fraud, forgery, manipulated ratings, infringing content and data sales are prohibited. Listings or accounts may be proportionately restricted for risk, violation or investigation.'),
    ],
  },
  'driver-terms': {
    title: ['شروط السائقين والمشغلين', 'Driver and Operator Terms'],
    intro: ['تكمل هذه الشروط شروط الاستخدام لكل سائق أو مشغل يظهر أو يستجيب لطلبات المعدات.', 'These terms supplement the Terms for every Driver or Operator appearing in or responding to equipment Requests.'],
    sections: [
      section('المؤهلات والرخص', 'Qualifications and licences', 'يجب امتلاك الرخص والمؤهلات والخبرة المناسبة للفئة وتجديدها، وعدم قبول عمل خارج الكفاءة أو الصلاحية النظامية.', 'Hold and maintain licences, qualifications and experience appropriate to the category, and do not accept work outside competence or legal authority.'),
      section('الملف والتوفر', 'Profile and availability', 'يجب تحديث الفئات والموقع التقريبي والتوفر والخبرة. الظهور في البحث لا يضمن عملاً أو دخلاً أو أهلية لكل موقع.', 'Keep categories, approximate location, availability and experience current. Search visibility does not guarantee work, income or eligibility for every site.'),
      section('السلامة واللياقة', 'Safety and fitness', 'يلتزم السائق بتعليمات المصنع والموقع ومعدات الوقاية والفحص قبل التشغيل، ولا يعمل تحت تأثير مسكر أو مادة أو إرهاق يجعل التشغيل غير آمن.', 'Follow manufacturer and site instructions, PPE and pre-operation inspection. Never operate while impaired by alcohol, drugs, medication or fatigue.'),
      section('التشغيل المشروع', 'Lawful operation', 'يلتزم بأنظمة المرور والعمل والسلامة والتصاريح حيث تنطبق، ويوقف العمل ويرفع الخطر عند عدم صلاحية المعدة أو الموقع.', 'Comply with traffic, work, safety and permit rules where applicable, and stop and escalate when equipment or site is unsafe.'),
      section('الحساب والمؤهلات', 'Account and credentials', 'يحظر مشاركة الحساب أو الرخصة أو تمكين شخص آخر من العمل باسم السائق. يبلغ عن فقد الحساب أو انتهاء المؤهل أو القيد المؤثر.', 'Do not share an account or licence or let another person work under your identity. Report compromise, expiry or relevant restrictions.'),
      section('التواصل والحضور', 'Communication and attendance', 'يؤكد تفاصيل المهمة ويتواصل باحترام ويحضر في الموعد. إذا تعذر الحضور يبلغ فوراً ولا يؤكد بدءاً أو إكمالاً غير صحيح.', 'Confirm job details, communicate respectfully and attend as agreed. If unable, notify promptly and never falsely confirm commencement or completion.'),
      section('الحوادث والمخالفات', 'Incidents and violations', 'يوقف التشغيل ويطلب المساعدة ويبلغ المسؤولين والجهات والمؤمن والدعم بحسب الحالة ويحفظ الأدلة. المسؤولية والغرامات تتبع النظام والسلوك لا تخصيصاً آلياً.', 'Stop operation, seek help, notify responsible parties, authorities, insurer and support as appropriate, and preserve evidence. Liability and fines follow law and conduct, not automatic allocation.'),
      section('الخصوصية والسلوك', 'Privacy and conduct', 'لا تستخدم بيانات الأطراف إلا للمهمة، ولا تتحرش أو تهدد أو ترسل رسائل مزعجة أو تصور أشخاصاً أو مواقع حساسة دون سند.', 'Use participant data only for the job. Do not harass, threaten, spam or record people or sensitive sites without a lawful basis.'),
      section('طبيعة العلاقة', 'Nature of relationship', 'Heavyar سوق تقني ولا يضمن وظيفة أو حداً أدنى من المهام. لا تحسم هذه الشروط وحدها الصفة الوظيفية أو التعاقدية؛ تحددها الوقائع والترتيب الفعلي والنظام.', 'Heavyar is a technology marketplace and does not guarantee employment or minimum jobs. These terms alone do not determine employment or contractor status; facts, actual arrangements and law do.'),
      section('التقييد والحقوق', 'Restriction and rights', 'يجوز تقييد الظهور أو الحساب لسلوك غير آمن أو احتيالي أو مؤهل منتهي أو تحقيق، بصورة متناسبة ومع الحقوق. لا تعد الشارة ضمان سلامة أو اعتماداً حكومياً.', 'Visibility or accounts may be proportionately restricted for unsafe or fraudulent conduct, expired credentials or investigation, subject to rights. A badge is not a safety guarantee or government endorsement.'),
    ],
  },
  verification: {
    title: ['سياسة التحقق والشارات', 'Verification and Badge Policy'],
    intro: ['أي تحقق أو شارة محدد النطاق والزمن ولا يحول Heavyar إلى جهة حكومية أو جهة ترخيص أو ضامن.', 'Any verification or badge is limited in scope and time and does not make Heavyar a government authority, licensing body or guarantor.'],
    sections: [
      section('الوضع الحالي', 'Current status', 'Nafath غير مفعلة في إصدار iOS الحالي، ولا يجمع الإصدار هوية وطنية أو جواز سفر أو مستند هوية حكومي. الحساب العادي ليس تحققاً حكومياً.', 'Nafath is not active in the current iOS release, which does not collect a national ID, passport or government identity document. An ordinary account is not government verification.'),
      section('بيانات المنشأة', 'Business information', 'رقم السجل التجاري أو بيانات المنشأة المدخلة معلومات عمل عادية ما لم تعرض Heavyar شارة محددة بعد عملية معلنة.', 'Submitted commercial-registration or business data is ordinary business information unless Heavyar displays a specific badge after a disclosed process.'),
      section('نطاق الشارة', 'Badge scope', 'تعني الشارة فقط أن المعلومة أو الوثيقة المسماة فحصت وفق العملية المتاحة في وقت محدد. لا تحل شارة الهوية محل رخصة النشاط أو بطاقة التشغيل.', 'A badge means only that the named information or document was checked under the available process at a point in time. Identity does not replace an activity licence or operating card.'),
      section('ما لا تعنيه الشارة', 'What a badge does not mean', 'الشارة ليست اعتماداً حكومياً ولا ضماناً للسلامة أو الملاءة أو السلوك أو نجاح المعاملة ولا توصية من Heavyar.', 'A badge is not government endorsement, a safety, solvency, conduct or transaction guarantee, or a Heavyar recommendation.'),
      section('الصلاحية والسحب', 'Validity and revocation', 'قد تنتهي الوثيقة أو تتغير. يجوز طلب تحديثها أو تعليق الشارة أو سحبها عند انتهاء الصلاحية أو التناقض أو الاشتباه مع مراجعة مناسبة.', 'A document may expire or change. Heavyar may request an update, suspend or revoke a badge for expiry, inconsistency or suspicion with appropriate review.'),
      section('ميزات مستقبلية', 'Future features', 'لا تعد السياسة بإطلاق Nafath أو جمع هوية حكومية أو بيانات بنك. أي ميزة جديدة تتطلب إفصاحات وضوابط مناسبة قبل تفعيلها.', 'This Policy does not promise Nafath, government-ID or bank-data collection. Any new feature requires appropriate disclosures and controls before activation.'),
      section('الإبلاغ', 'Reporting', 'أبلغ الدعم عن معلومة أو شارة قديمة أو مضللة دون نشر المستندات علناً. لا تمنع الشارة التحقق من الجهة المصدرة أو المختصة.', 'Report outdated or misleading information or badges to support without publishing documents. A badge never prevents checking with the issuer or authority.'),
    ],
  },
  'restricted-activities': {
    title: ['سياسة الأنشطة المقيدة والمنظمة', 'Restricted and Regulated Activities'],
    intro: ['تختلف المتطلبات بحسب المعدة والنشاط والدور والموقع. لا تمنح Heavyar ترخيصاً ولا تفترض قاعدة واحدة لكل المعدات.', 'Requirements vary by equipment, activity, role and location. Heavyar does not issue licences or assume one rule applies to all equipment.'],
    sections: [
      section('متطلبات النشاط', 'Activity requirements', 'يجب الحصول على أي سجل أو ترخيص أو تصريح أو بطاقة تشغيل أو موافقة موقع أو تأمين تطلبه الأنظمة أو الجهة المختصة قبل العرض أو الطلب أو التشغيل.', 'Obtain any registration, licence, permit, operating card, site approval or insurance required by law or a competent authority before listing, requesting or operating.'),
      section('الملكية والتفويض', 'Ownership and authority', 'يحظر عرض أو نقل أو تشغيل معدة مسروقة أو غير مفوضة أو إخفاء قيد يمنع الاستخدام. يجوز طلب إثبات وتقييد المعاملة للمراجعة.', 'Do not list, transport or operate stolen or unauthorized equipment or conceal a restriction preventing use. Proof may be requested and the transaction restricted for review.'),
      section('الشاحنات دون سائق', 'Truck rental without a Driver', 'في الفرع السعودي المنظم لا تقبل معاملة truck-rental-without-driver حتى تثبت القدرة النظامية من حالة المنشأة ووثائق النشاط وبطاقة التشغيل والملكية أو التفويض بحسب المطلوب. تصريح نقل فردي ليس تلقائياً ترخيصاً لتأجير الشاحنات.', 'For the regulated Saudi branch, a truck-rental-without-driver transaction is not accepted until lawful capability is established through business status, activity documents, operating card and ownership or authority as required. An individual freight authorization is not automatically a truck-rental licence.'),
      section('الاستخدام الخطر أو غير المشروع', 'Unsafe or unlawful use', 'يحظر الإيذاء أو تجاوز حدود الحمولة أو تعطيل السلامة أو العمل في موقع محظور أو النقل غير المشروع.', 'Harm, exceeding load limits, disabling safety systems, work at prohibited sites and unlawful transport are prohibited.'),
      section('الأنشطة والأصول المحظورة', 'Prohibited activities and assets', 'يحظر الاحتيال وغسل الأموال والتهريب والنشاط الخاضع لعقوبات أو المحظور، والمعدات المزورة أو المسروقة أو غير الآمنة، والخدمة بلا ترخيص مطلوب.', 'Fraud, money laundering, smuggling, sanctioned or unlawful activity, counterfeit, stolen or unsafe equipment, and services lacking required licences are prohibited.'),
      section('المستندات المضللة', 'Misleading documents', 'يحظر تزوير أو تعديل الرخص والتصاريح والسجلات وبطاقات التشغيل أو استخدام مستند الغير. الوثيقة لا توسع نطاق النشاط الذي تغطيه.', 'Do not forge or alter licences, permits, registrations or operating cards or use another person\'s document. A document does not authorize activity outside its scope.'),
      section('التقييد والإزالة', 'Restriction and removal', 'يجوز إيقاف عرض أو طلب أو حساب للخطر أو نقص متطلب أو طلب صحيح من جهة مختصة بصورة متناسبة، ولا يعد ذلك حكماً نهائياً بالمسؤولية.', 'A listing, Request or account may be proportionately paused for risk, an incomplete requirement or valid authority request, without being a final liability decision.'),
      section('الجهات المختصة', 'Competent authorities', 'قد تحفظ Heavyar سجلات وتستجيب لطلب نظامي. يجب إبلاغ الطوارئ أو الشرطة أو المرور أو الجهة التنظيمية مباشرة عندما تتطلب الواقعة.', 'Heavyar may preserve records and respond to a lawful request. Users must directly contact emergency services, police, traffic or regulators when the incident requires.'),
    ],
  },
  'acceptable-use': {
    title: ['سياسة الاستخدام المقبول والسلوك المحظور', 'Acceptable Use and Prohibited Conduct'],
    intro: ['تحمي هذه السياسة المستخدمين والمعدات والأنظمة وتطبق مع شروط الاستخدام والسياسات الخاصة بالأدوار.', 'This Policy protects users, equipment and systems and applies with the Terms and role policies.'],
    sections: [
      section('الحسابات والهوية', 'Accounts and identity', 'يحظر الحساب الوهمي والانتحال ومشاركة الحساب وتجاوز التحقق أو القيود واستخدام بيانات الغير دون سند.', 'Fake accounts, impersonation, account sharing, bypassing verification or restrictions and unauthorized use of another person\'s data are prohibited.'),
      section('العروض والمستندات', 'Listings and documents', 'يحظر عرض معدات مسروقة أو غير مفوضة، والمعلومات أو الصور أو الأسعار المضللة، والتزوير، وإخفاء عيب جوهري معلوم.', 'Stolen or unauthorized equipment, misleading information, images or prices, forgery and concealment of a known material defect are prohibited.'),
      section('السلوك والتواصل', 'Conduct and communications', 'يحظر التحرش والتهديد والكراهية والتمييز والابتزاز والرسائل المزعجة والروابط الخبيثة ونشر بيانات شخصية دون سند.', 'Harassment, threats, hate, discrimination, extortion, spam, malicious links and unauthorized publication of personal data are prohibited.'),
      section('الدفع والتقييمات', 'Payments and ratings', 'يحظر الدفع دون تفويض والاعتراض البنكي الاحتيالي وتزوير السداد أو الاسترجاع والتلاعب بالتقييمات أو الانتقام من تقييم صادق.', 'Unauthorized payments, fraudulent chargebacks, false payment or refund evidence, rating manipulation and retaliation for genuine reviews are prohibited.'),
      section('الأمن والتشغيل الآلي', 'Security and automation', 'يحظر اختبار الثغرات دون تصريح أو تعطيل الخدمة أو البرمجيات الضارة أو الكشط والروبوتات والحسابات الآلية التي تضر الخدمة أو تتجاوز الضوابط.', 'Unauthorized vulnerability testing, disruption, malware, scraping, bots and automated accounts that harm the service or evade controls are prohibited.'),
      section('البيانات والخصوصية', 'Data and privacy', 'لا تجمع أو تبع أو تعيد استخدام بيانات المستخدم خارج المعاملة، ولا تطلب كلمة مرور أو بيانات بطاقة أو CVV، ولا تراقب الأشخاص دون أساس.', 'Do not collect, sell or reuse user data outside a transaction, request passwords, card data or CVV, or monitor people without a lawful basis.'),
      section('الملكية الفكرية', 'Intellectual property', 'يحظر انتهاك العلامات أو حقوق النشر ورفع محتوى غير مرخص ونسخ أو هندسة المنصة عكسياً إلا بالقدر الذي لا يجوز تقييده.', 'Trademark or copyright infringement, unlicensed uploads, and copying or reverse engineering are prohibited except where restriction is unlawful.'),
      section('الإنفاذ والإبلاغ', 'Enforcement and reporting', 'يجوز إزالة المحتوى أو تقييد وظيفة أو حساب أو حفظ الأدلة أو الإحالة للجهة المختصة بحسب الخطر، مع الحقوق النظامية. أبلغ الدعم بأقل بيانات لازمة.', 'Heavyar may remove content, restrict features or accounts, preserve evidence or refer matters to authorities proportionately to risk and subject to statutory rights. Report with minimum necessary data.'),
    ],
  },
};

const labels = {
  terms: ['شروط الاستخدام', 'Terms of Use'], privacy: ['سياسة الخصوصية', 'Privacy Policy'],
  'refund-policy': ['الإلغاء والاسترجاع', 'Cancellation and Refunds'], disputes: ['الشكاوى والنزاعات', 'Complaints and Disputes'],
  'provider-terms': ['شروط مقدمي الخدمة', 'Provider Terms'], 'driver-terms': ['شروط السائقين', 'Driver Terms'],
  verification: ['التحقق والشارات', 'Verification and Badges'], 'restricted-activities': ['الأنشطة المقيدة', 'Restricted Activities'],
  'acceptable-use': ['الاستخدام المقبول', 'Acceptable Use'], 'account-deletion': ['حذف الحساب', 'Account Deletion'],
};

const related = {
  terms: ['privacy', 'refund-policy', 'disputes', 'provider-terms', 'driver-terms', 'acceptable-use'],
  privacy: ['terms', 'verification'], 'refund-policy': ['terms', 'disputes'], disputes: ['terms', 'refund-policy', 'acceptable-use'],
  'provider-terms': ['terms', 'verification', 'restricted-activities'], 'driver-terms': ['terms', 'verification', 'acceptable-use'],
  verification: ['privacy', 'provider-terms', 'restricted-activities'], 'restricted-activities': ['terms', 'provider-terms', 'acceptable-use'],
  'acceptable-use': ['terms', 'disputes', 'privacy'],
};

const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

export function hasLegalPage(key) { return Object.hasOwn(pages, key); }
export function legalSectionCount(key) { return pages[key]?.sections.length || 0; }

export function renderLegalPage(key, locale) {
  const page = pages[key];
  if (!page) throw new Error('Unknown legal page');
  const en = locale === 'en';
  const pick = pair => pair[en ? 1 : 0];
  const prefix = en ? '/en' : '';
  const toc = page.sections.map((item, index) => `<li><a href="#section-${index + 1}"><span>${index + 1}</span>${escape(pick(item.title))}</a></li>`).join('');
  const content = page.sections.map((item, index) => `<section class="legal-section" id="section-${index + 1}"><h2>${index + 1}. ${escape(pick(item.title))}</h2><p>${escape(pick(item.text))}</p>${item.bullets.length ? `<ul>${item.bullets.map(bullet => `<li>${escape(pick(bullet))}</li>`).join('')}</ul>` : ''}</section>`).join('');
  const links = (related[key] || []).map(target => `<a href="${prefix}/${target}">${escape(pick(labels[target]))}</a>`).join('');
  return `<main class="legal-page" id="main-content"><header class="inner-hero"><div class="site-container inner-hero-copy"><p class="eyebrow eyebrow-light">${en ? 'Heavyar policies' : 'سياسات Heavyar'}</p><h1>${escape(pick(page.title))}</h1><p>${escape(pick(page.intro))}</p></div></header><div class="site-container legal-layout"><article class="legal-content"><div class="page"><div class="legal-meta"><strong>${en ? 'Effective and last updated' : 'تاريخ النفاذ وآخر تحديث'}</strong><span>${escape(pick(UPDATED))}</span></div><nav class="legal-toc" aria-label="${en ? 'Table of contents' : 'فهرس المحتويات'}"><h2>${en ? 'Table of contents' : 'فهرس المحتويات'}</h2><ol>${toc}</ol></nav>${content}<aside class="legal-related"><h2>${en ? 'Related policies' : 'سياسات مرتبطة'}</h2><div>${links}<a href="${prefix}/account-deletion">${escape(pick(labels['account-deletion']))}</a></div></aside><div class="legal-contact"><h2>${en ? 'Contact and complaints' : 'التواصل والشكاوى'}</h2><p>${en ? 'Contact Heavyar Support at' : 'تواصل مع دعم Heavyar عبر'} <a href="mailto:${EMAIL}">${EMAIL}</a>. ${en ? 'Do not send passwords or full payment-card details.' : 'لا ترسل كلمات المرور أو بيانات بطاقة الدفع الكاملة.'}</p></div></div></article></div></main>`;
}
